name: Check links on push

on: push
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - uses: gaurav-nelson/github-action-markdown-link-check@9574206dc60cad6bb68a9898c14300773c64bb40
      with:
        use-quiet-mode: "yes"
        check-modified-files-only: "yes"
# Documentation available here: https://github.com/marketplace/actions/markdown-link-check
